theme: jekyll-theme-cayman
title: [Movement Synthesizer](https://caitlincoffey.github.io/Movement-Synthesizer/)
description: [Music Produced from Movement Data](https://caitlincoffey.github.io/Movement-Synthesizer/)
